In [2]:
import pandas as pd

In [3]:
df_CG = pd.read_csv('/home/art/test_AB_projeto/data/control_group.csv')

In [4]:
df_CG

   Campaign Name;Date;Spend [USD];# of Impressions;Reach;# of Website Clicks;# of Searches;# of View Content;# of Add to Cart;# of Purchase
0   Control Campaign;1.08.2019;2280;82702;56930;70...
1   Control Campaign;2.08.2019;1757;121040;102513;...
2   Control Campaign;3.08.2019;2343;131711;110862;...
3   Control Campaign;4.08.2019;1940;72878;61235;30...
4              Control Campaign;5.08.2019;1835;;;;;;;
5   Control Campaign;6.08.2019;3083;109076;87998;4...
6   Control Campaign;7.08.2019;2544;142123;127852;...
7   Control Campaign;8.08.2019;1900;90939;65217;72...
8   Control Campaign;9.08.2019;2813;121332;94896;6...
9   Control Campaign;10.08.2019;2149;117624;91257;...
10  Control Campaign;11.08.2019;2490;115247;95843;...
11  Control Campaign;12.08.2019;2319;116639;100189...
12  Control Campaign;13.08.2019;2697;82847;68214;6...
13  Control Campaign;14.08.2019;1875;145248;118632...
14  Control Campaign;15.08.2019;2774;132845;102479...
15  Control Campaign;16.08.2019;2024;71274;42859;5...
16  Control Campaign;17.08.2019;2177;119612;106518...
17  Control Campaign;18.08.2019;1876;108452;96518;...
18  Control Campaign;19.08.2019;2596;107890;81268;...
19  Control Campaign;20.08.2019;2675;113430;78625;...
20  Control Campaign;21.08.2019;1803;74654;59873;5...
21  Control Campaign;22.08.2019;2939;105705;86218;...
22  Control Campaign;23.08.2019;2496;129880;109413...
23  Control Campaign;24.08.2019;1892;72515;51987;4...
24  Control Campaign;25.08.2019;1962;117006;100398...
25  Control Campaign;26.08.2019;2233;124897;98432;...
26  Control Campaign;27.08.2019;2061;104678;91579;...
27  Control Campaign;28.08.2019;2421;141654;125874...
28  Control Campaign;29.08.2019;2375;92029;74192;8...
29  Control Campaign;30.08.2019;2324;111306;88632;...

In [5]:
df_CG.info

<bound method DataFrame.info of    Campaign Name;Date;Spend [USD];# of Impressions;Reach;# of Website Clicks;# of Searches;# of View Content;# of Add to Cart;# of Purchase
0   Control Campaign;1.08.2019;2280;82702;56930;70...
1   Control Campaign;2.08.2019;1757;121040;102513;...
2   Control Campaign;3.08.2019;2343;131711;110862;...
3   Control Campaign;4.08.2019;1940;72878;61235;30...
4              Control Campaign;5.08.2019;1835;;;;;;;
5   Control Campaign;6.08.2019;3083;109076;87998;4...
6   Control Campaign;7.08.2019;2544;142123;127852;...
7   Control Campaign;8.08.2019;1900;90939;65217;72...
8   Control Campaign;9.08.2019;2813;121332;94896;6...
9   Control Campaign;10.08.2019;2149;117624;91257;...
10  Control Campaign;11.08.2019;2490;115247;95843;...
11  Control Campaign;12.08.2019;2319;116639;100189...
12  Control Campaign;13.08.2019;2697;82847;68214;6...
13  Control Campaign;14.08.2019;1875;145248;118632...
14  Control Campaign;15.08.2019;2774;132845;102479...
15  Control Campaign;16.08.2019;2024;71274;42859;5...
16  Control Campaign;17.08.2019;2177;119612;106518...
17  Control Campaign;18.08.2019;1876;108452;96518;...
18  Control Campaign;19.08.2019;2596;107890;81268;...
19  Control Campaign;20.08.2019;2675;113430;78625;...
20  Control Campaign;21.08.2019;1803;74654;59873;5...
21  Control Campaign;22.08.2019;2939;105705;86218;...
22  Control Campaign;23.08.2019;2496;129880;109413...
23  Control Campaign;24.08.2019;1892;72515;51987;4...
24  Control Campaign;25.08.2019;1962;117006;100398...
25  Control Campaign;26.08.2019;2233;124897;98432;...
26  Control Campaign;27.08.2019;2061;104678;91579;...
27  Control Campaign;28.08.2019;2421;141654;125874...
28  Control Campaign;29.08.2019;2375;92029;74192;8...
29  Control Campaign;30.08.2019;2324;111306;88632;...                                                                                      >

In [6]:
df_CG

   Campaign Name;Date;Spend [USD];# of Impressions;Reach;# of Website Clicks;# of Searches;# of View Content;# of Add to Cart;# of Purchase
0   Control Campaign;1.08.2019;2280;82702;56930;70...
1   Control Campaign;2.08.2019;1757;121040;102513;...
2   Control Campaign;3.08.2019;2343;131711;110862;...
3   Control Campaign;4.08.2019;1940;72878;61235;30...
4              Control Campaign;5.08.2019;1835;;;;;;;
5   Control Campaign;6.08.2019;3083;109076;87998;4...
6   Control Campaign;7.08.2019;2544;142123;127852;...
7   Control Campaign;8.08.2019;1900;90939;65217;72...
8   Control Campaign;9.08.2019;2813;121332;94896;6...
9   Control Campaign;10.08.2019;2149;117624;91257;...
10  Control Campaign;11.08.2019;2490;115247;95843;...
11  Control Campaign;12.08.2019;2319;116639;100189...
12  Control Campaign;13.08.2019;2697;82847;68214;6...
13  Control Campaign;14.08.2019;1875;145248;118632...
14  Control Campaign;15.08.2019;2774;132845;102479...
15  Control Campaign;16.08.2019;2024;71274;42859;5...
16  Control Campaign;17.08.2019;2177;119612;106518...
17  Control Campaign;18.08.2019;1876;108452;96518;...
18  Control Campaign;19.08.2019;2596;107890;81268;...
19  Control Campaign;20.08.2019;2675;113430;78625;...
20  Control Campaign;21.08.2019;1803;74654;59873;5...
21  Control Campaign;22.08.2019;2939;105705;86218;...
22  Control Campaign;23.08.2019;2496;129880;109413...
23  Control Campaign;24.08.2019;1892;72515;51987;4...
24  Control Campaign;25.08.2019;1962;117006;100398...
25  Control Campaign;26.08.2019;2233;124897;98432;...
26  Control Campaign;27.08.2019;2061;104678;91579;...
27  Control Campaign;28.08.2019;2421;141654;125874...
28  Control Campaign;29.08.2019;2375;92029;74192;8...
29  Control Campaign;30.08.2019;2324;111306;88632;...

In [7]:
df_CG.head()

  Campaign Name;Date;Spend [USD];# of Impressions;Reach;# of Website Clicks;# of Searches;# of View Content;# of Add to Cart;# of Purchase
0  Control Campaign;1.08.2019;2280;82702;56930;70...
1  Control Campaign;2.08.2019;1757;121040;102513;...
2  Control Campaign;3.08.2019;2343;131711;110862;...
3  Control Campaign;4.08.2019;1940;72878;61235;30...
4             Control Campaign;5.08.2019;1835;;;;;;;

In [8]:
df_CG.describe()

       Campaign Name;Date;Spend [USD];# of Impressions;Reach;# of Website Clicks;# of Searches;# of View Content;# of Add to Cart;# of Purchase
count                                                  30
unique                                                 30
top     Control Campaign;1.08.2019;2280;82702;56930;70...
freq                                                    1

In [11]:
df_CG.describe()

       Campaign Name;Date;Spend [USD];# of Impressions;Reach;# of Website Clicks;# of Searches;# of View Content;# of Add to Cart;# of Purchase
count                                                  30
unique                                                 30
top     Control Campaign;1.08.2019;2280;82702;56930;70...
freq                                                    1